### ISSUE TITLE
Pandas and pyarrow version incompatibility?

### ISSUE THREAD

**Issue by rortizmerino** [mgeraeds/hires-processing#3]
I got the following error message:

```
Traceback (most recent call last):
  File "/scratch/rortizmerino/HRS/hires-processing/src/calc/gradient.py", line 1, in <module>
    import dfm_tools as dfmt
  File "/scratch/rortizmerino/conda/hires_env/lib/python3.11/site-packages/dfm_tools/__init__.py", line 10, in <module>
    from dfm_tools.download import *
  File "/scratch/rortizmerino/conda/hires_env/lib/python3.11/site-packages/dfm_tools/download.py", line 9, in <module>
    import pandas as pd
  File "/scratch/rortizmerino/conda/hires_env/lib/python3.11/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas.compat import (
  File "/scratch/rortizmerino/conda/hires_env/lib/python3.11/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/scratch/rortizmerino/conda/hires_env/lib/python3.11/site-packages/pandas/compat/pyarrow.py", line 10, in <module>
    _palv = Version(Version(pa.__version__).base_version)
                            ^^^^^^^^^^^^^^
AttributeError: module 'pyarrow' has no attribute '__version__'
```

Perhaps my installation went wrong at some point, checking that out but may be worthwhile to keep in mind in relation to issue #1

**Comment by rortizmerino** [comment]
Found a few related issues apparently solved by re-installing or upgrading pyarrow. Currently, `conda list` shows:

```
pyarrow                   11.0.0          py311hd8e8d9b_1
pyarrow-hotfix            0.6                pyhd8ed1ab_0    conda-forge
```
Latest version in conda-forge is 15.0.0 , latest version using pip is 11.0.0

**Comment by rortizmerino** [comment]
ran `pip install -r requirements.txt` once again and pandas was downgraded to v1.5.3 from 2.2.0. Then, `lib/python3.11/site-packages/pandas/compat/pyarrow.py` has a similar version check routine than above but checking for versions lower than 10 instead of lower than 15.

Overrode the check with:

```
if hasattr(pa, '__version__'):
   _palv = Version(pa.__version__)
else:
   _palv = Version("0.0.0")  # Default version if __version__ attribute is not available
```
in `lib/python3.11/site-packages/pandas/compat/pyarrow.py`, but it's not really a fix as the file gets automatically overwritten when updating pandas.

Keeping open for future reference
